<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.util.concurrent.FutureUtilsTests" tests="4" skipped="0" failures="0" errors="0" timestamp="2022-11-30T11:07:23" hostname="WKS-SE-RPL" time="0.064">
  <properties/>
  <testcase name="callAsyncNormalExecutor()" classname="org.springframework.util.concurrent.FutureUtilsTests" time="0.034"/>
  <testcase name="callAsyncException()" classname="org.springframework.util.concurrent.FutureUtilsTests" time="0.007"/>
  <testcase name="callAsyncNormal()" classname="org.springframework.util.concurrent.FutureUtilsTests" time="0.001"/>
  <testcase name="callAsyncExceptionExecutor()" classname="org.springframework.util.concurrent.FutureUtilsTests" time="0.022"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
